version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.10-bullseye"
        NODE_VERSION: "16"
    init: true
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      API_URL: http://api:5000
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data: null
