version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14-bullseye
    init: true
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data: null
