version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    init: true
    hostname: app
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
