name: Release the API

# Only run on pushes to trunk and on changes to the API
# source directory.
on:
  push:
    branches:
    - trunk
    paths:
    - .github/workflows/release-api.yml
    - api/**

concurrency:
  group: ${{ github.workflow }}-staging
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      # Checkout the repository in the CI worker.
    - name: Checkout repository
      uses: actions/checkout@v2

      # Set up Node.js.
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

      # Cache dependencies.
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

      # Install dependencies.
    - name: Install dependencies
      run: npm ci

      # Build the project.
    - name: Build the project
      run: npm run build

      # Deploy changes.
    - name: Deploy changes to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1
      run: npx cdk deploy --require-approval never
