name: Release the chatbot

# Only run on pushes to trunk and on changes to the chatbot
# source directory.
on:
  push:
    branches:
    - trunk
    paths:
    - .github/workflows/release-bot.yml
    - bot/**

concurrency:
  group: ${{ github.workflow }}-staging
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot
    steps:
      # Checkout the repository in the CI worker.
    - name: Checkout repository
      uses: actions/checkout@v2

      # Set up Python.
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

      # Install Poetry.
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

      # Add Poetry to the runner PATH.
    - name: Add Poetry to PATH
      run: |
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      # Validate the pyproject.toml file.
    - name: Check pyproject.toml validity
      run: poetry check --no-interaction

      # Build the project.
    - name: Build the project
      run: poetry build

      # Log in to the Heroku platform.
    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

      # Build and push the image.
    - name: Build and push image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push worker --app discord-builder

      # Trigger a release on Heroku.
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release worker --app discord-builder
